// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtinCarju4Ez48WyJ_G9pedF8_Z9M1smU',
    appId: '1:442860237005:web:44900a49d356c747207984',
    messagingSenderId: '442860237005',
    projectId: 'house-of-reels',
    authDomain: 'house-of-reels.firebaseapp.com',
    storageBucket: 'house-of-reels.appspot.com',
    measurementId: 'G-4S5GM56QG2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOhCwzZx9tHGhB53eHoSbJmaZqIlUVH0U',
    appId: '1:442860237005:android:595ba7338c6aed37207984',
    messagingSenderId: '442860237005',
    projectId: 'house-of-reels',
    storageBucket: 'house-of-reels.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6DQT96pPDQOgD93Y0dE4KqdCae-gIvkE',
    appId: '1:442860237005:ios:9b41b752337e0e6c207984',
    messagingSenderId: '442860237005',
    projectId: 'house-of-reels',
    storageBucket: 'house-of-reels.appspot.com',
    iosBundleId: 'com.example.houseOfReels',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA6DQT96pPDQOgD93Y0dE4KqdCae-gIvkE',
    appId: '1:442860237005:ios:463cb561ece255cd207984',
    messagingSenderId: '442860237005',
    projectId: 'house-of-reels',
    storageBucket: 'house-of-reels.appspot.com',
    iosBundleId: 'com.example.houseOfReels.RunnerTests',
  );
}
